### ISSUE TITLE
Pods Use of undeclared type Issues

### ISSUE THREAD

**Issue by FlowBo** [MailOnline/ImageViewer#124]
Hello,
I added the ImageViewer via pods to my project and tried to make use of the Github Swift Example Code. When I try to build I always get these errors: 

Use of undeclared type 'GalleryDisplacedViewsDataSource'
Use of undeclared type 'GalleryItemsDataSource' 
Use of undeclared type 'GalleryItemsDelegate'
Use of undeclared type 'ItemBaseController'
Use of undeclared type 'ItemViewControllerBlock'

It seams that the pod file is not correctly linked.

**Comment by zfoltin** [comment]
Will release 4.1.0 soon which should solve this issue

**Comment by seifeet** [comment]
I still have the same issue with"GalleryItemsDatasource"

Use of undeclared type 'GalleryItemsDatasource'

**Comment by hqs5678** [comment]
The problem still exists with 4.1.0 !!!!

**Comment by hqs5678** [comment]
version 4.0 is ok
pod 'ImageViewer', '4.0'

**Comment by a-r-w** [comment]
You are likely missing the:

`import ImageViewer
`
statement
