### ISSUE TITLE
Wrong image shows when opening images with identical filenames in different directories

### ISSUE THREAD

**Issue by seieibob** [MailOnline/ImageViewer#138]
I have an app for reading comic books, where the images for each chapter are stored in their own folders. The images are typically numbered, so most directories will have a "1.jpg" or something similar as the first file. When you get done reading a few chapters, the images shown in the image viewer start to show images from other chapters, and the problem seems to be name similarity.

Here's a test folder structure:
```
Test1/
    1.jpg
Test2/
    1.jpg
```

You can reproduce my problem by opening `Test1/1.jpg`, then opening `Test2/1.jpg`. From this point, the image viewer will show `Test2/1.jpg` if you try to open `Test1/1.jpg`, despite being passed a UIImage created from the latter. Importantly, this is only for images named `1.jpg` in this example. If I open an image with another name, there are no problems. 

The problem will continue to occur even if I delete `Test2/1.jpg`. The incorrect image is reflected in the Gallery view as well.

I hope that made sense! Thank you for your time.

**Comment by Krisiacik** [comment]
Hi,

I don't think this should be solved on our side.(i.e. inside the framework) You could implement a mapping solution..something that will pick the right file on your side and provide the imageviewer model object on viewer's side.

**Comment by seieibob** [comment]
That's the thing, though. The imageviewer is already being fed separate GalleryItem instances with different UIImage data, and the problem persists. I'll put together an example for you to try out.

Something I forgot to mention is that this only happens on the device, and not on the simulator.

**Comment by seieibob** [comment]
I've made a test example at https://github.com/seieibob/ImageViewerTest.

**Comment by seieibob** [comment]
I "fixed" this on my end by tacking a random string to the end of every file's name to ensure uniqueness. This doesn't solve the root problem, and is only a useful approach when working with copies of files, though. My app unpacks archives to a folder and reads the images from that folder, so it's okay to modify those file names, but I imagine that it isn't a good idea to do this with non-temporary files.

**Comment by seieibob** [comment]
I'm dumb. The issue is the difference between `let image = UIImage(named: "path")` and `let image = UIImage(contentsOfFile: "path")`. The first looks for a cached image with the given name, and was what I was using. Since my app regenerates the same folder that all the images are unpacked into, the name of a new file might be the same as one of the old cached paths, yielding an old image. The solution here is to use the second (`contentsOfFile`) method.

See https://stackoverflow.com/a/17801103 for more.
