### ISSUE TITLE
Problem with dragging down(in opposition to up) on an image in imageviewcontroller

### ISSUE THREAD

**Issue by wongmac** [MailOnline/ImageViewer#38]
For some reason when I try to dismiss an image by swiping down dragging the image down, the image becomes "stuck" to the bottom. Dismissing the image by swiping up works perfectly, as well as through close button. Looked at the code, and both directions should work just fine with the pangesture. Could you help me out?
![aaaa](https://cloud.githubusercontent.com/assets/16651313/16570772/0a50b2fc-4212-11e6-977f-a0edf0be7a8a.gif)

**Comment by zfoltin** [comment]
@wongmac can you try and run the Example? Does that work as expected? Can't really think of any reason why it would stuck like that

**Comment by paulcirstean** [comment]
I'm experiencing similar behavior.

**Comment by Krisiacik** [comment]
Guys, sorry to hear about your troubles :( . We had this issue, true, but we fixed it in 
https://github.com/MailOnline/ImageViewer/releases/tag/2.0.3

Are you sure your dependency to that particular version (or later) is set up correctly? 
@wongmac As you say the code looks correct, there's really no reason why this should not work.

Pls check and let us know.

**Comment by Krisiacik** [comment]
Guys, sorry to hear about your troubles :(

We had this issue in the past, but it was fixed in release 2.0.3 
https://github.com/MailOnline/ImageViewer/releases/tag/2.0.3

Are your sure you are pointing to an up-to-date version in your dependency setup?
@wongmac As you said, the code seems to be correct.. it should work.

Pls check your carthage/cocoapods and let us know.

**Comment by paulcirstean** [comment]
Just tested with 2.0.3 and it's still reproducible :( The sample app works correctly. Quite strange..

**Comment by Krisiacik** [comment]
Hi @paulcirstean,

hmmm...for completely inexplicable reasons the tags for 2.0.3 and 2.0.4 are in reverse order. 
Do you have any specific reason not to go with 2.0.6? That will have guaranteed to have the fix included.

**Comment by ahmedbaracat** [comment]
I have checked the example project and the difference is in that a new function was added to handle swipe ended case. I have used it with version 2.0 and the problem was fixed. The pod version needs to be updated.

```
func handleSwipeToDismissEnded(verticalVelocity: CGFloat, lastTouchPoint: CGPoint, targetOffset: CGFloat) {
        
        let velocity = abs(verticalVelocity)
        
        switch velocity {
            
        case 0 ..< thresholdVelocity:
            
            swipeToDismissCanceledAnimation()
            
        case thresholdVelocity ... cutOffVelocity:
        
            let offset = (verticalVelocity > 0) ? -targetOffset : targetOffset
            let touchPoint = (verticalVelocity > 0) ? -lastTouchPoint.y : lastTouchPoint.y
            
            swipeToDismissTransition.setParameters(touchPoint, targetOffset: offset, verticalVelocity: verticalVelocity)
            presentingViewController?.dismissViewControllerAnimated(true, completion: nil)
            
        default: break
        }
    }
```

**Comment by paulcirstean** [comment]
Works with 2.0.6. Thanks!
